### ISSUE TITLE
System logo zoom behaviour changed

### ISSUE THREAD

**Issue by joolswills** [RetroPie/EmulationStation#126] opened 2017-05-04 16:57 UTC
https://retropie.org.uk/forum/topic/10088/retropie-themes-zooming-in-logos/5

bisected to ac5e3ad95f34ac52bc925d618f37fe9b1717b42b

```
commit ac5e3ad95f34ac52bc925d618f37fe9b1717b42b
Author: D. Polders <zigurana@gmail.com>
Date:   Mon Mar 13 22:11:07 2017 +0100

    System Carousel feature, now with only a single commit!
```

**Comment by joolswills** [comment] 2017-05-04 17:02
Not sure if this is a bug or a by design change in behaviour (since the scale is now configurable by the theme). Open to fixing up carbon, or changing the default scaling in the code.

**Comment by joolswills** [comment] 2017-05-04 17:02
tagging @zigurana

**Comment by joolswills** [comment] 2017-05-04 17:09
this would restore the previous behaviour

```diff
diff --git a/es-app/src/views/SystemView.cpp b/es-app/src/views/SystemView.cpp
index 1024d84f..367a8b36 100644
--- a/es-app/src/views/SystemView.cpp
+++ b/es-app/src/views/SystemView.cpp
@@ -47,7 +47,7 @@ void SystemView::populate()
                        e.data.logo = std::shared_ptr<GuiComponent>(logo);
 
                        ImageComponent* logoSelected = new ImageComponent(mWindow);
-                       logoSelected->setMaxSize(Eigen::Vector2f(mCarousel.logoSize.x() * mCarousel.logoScale, mCarousel.logoSize.y() * mCarousel.logoScale));
+                       logoSelected->setMaxSize(Eigen::Vector2f(mCarousel.logoSize.x() * mCarousel.logoScale, mCarousel.logoSize.y() * mCarousel.logoScale * 0.70f));
                        logoSelected->applyTheme((*it)->getTheme(), "system", "logo", ThemeFlags::PATH | ThemeFlags::COLOR);
                        logoSelected->setPosition((mCarousel.logoSize.x() - logoSelected->getSize().x()) / 2,
                                (mCarousel.logoSize.y() - logoSelected->getSize().y()) / 2); // center
```

**Comment by pjft** [comment] 2017-05-04 17:15
It would seem like it. It may affect any current vertical carousel themes in development, but since they're using the carousel element explicitly, they can increase their logoScale value.

This change would seem to ensure previous themes behave as they did beforehand, so I'm supportive in principle for compatibility's sake.

**Comment by joolswills** [comment] 2017-05-04 17:18
could hardcoding the 0.7f just on the vertical scale could possibly affect new themes in a way they can't workaround ? Perhaps some additional logic to set a flag if there is no scale set to use the 0.7 reduction on the height ?

**Comment by zigurana** [comment] 2017-05-04 17:34
Hi, I feel the old behavior was messy, setting the maximum height to be some hard-coded relative value of the non-selected logo size. Maybe my new way is just as messy, just differently so, I am open to suggestions. 
In any case, for all legacy themes, this behaviour should be fixed via the default value for LogoScale (currently: LogoScale = 1.5f;). I kind of eye-balled that value,to be honest, so maybe it should be adjusted?
Re-introducing the hard-coded parameter would not be my preferece.

**Comment by pjft** [comment] 2017-05-04 17:37
Hm. The fact that this is a maxSize setting, capped on the Y axis seems to have existed to ensure that the default system strip always had a padding on top and on the bottom, for the system logos.

Now that we're allowing for vertical themes, and customizing logo sizes, we're opening several other vectors to control.

I agree that your option is likely the best, but it requires a few more changes then, as [it is initialized as 1.5f anyway](https://github.com/RetroPie/EmulationStation/blob/master/es-app/src/views/SystemView.cpp#L439), so detecting for whether the scale was explicitly set will be tricky.

An alternative (I don't know how to do it interactively in GitHub, sorry) is to:
- [split logoScale into logoScaleX and logoScaleY in SystemViewCarousel struct](https://github.com/RetroPie/EmulationStation/blob/master/es-app/src/views/SystemView.h#L31).

- [set the defaults to](https://github.com/RetroPie/EmulationStation/blob/master/es-app/src/views/SystemView.cpp#L439):
```
mCarousel.logoScaleX = 1.5f
mCarousel.logoScaleY = 1.5f * 0.7f;
```

and then, if it gets set in [getCarouselFromTheme](https://github.com/RetroPie/EmulationStation/blob/master/es-app/src/views/SystemView.cpp#L463), set both to the declared value:

```
if (elem->has("logoScale")) {
		mCarousel.logoScaleX = elem->get<float>("logoScale");
		mCarousel.logoScaleY = elem->get<float>("logoScale");
}
```

and then [use those two to the new values](https://github.com/RetroPie/EmulationStation/blob/master/es-app/src/views/SystemView.cpp#L50).

@zigurana : the 1.5f value was hardcoded indeed. The problem is that it's multiplied by yet another hardcoded constant when resizing it :P  

Agreed, it was messy. 

My proposal is just to initialize defaults to be compatible with the old themes, but open to consideration.

**Comment by joolswills** [comment] 2017-05-04 17:39
I'm happy to go with the additional logic to set x/y depending if it's in the theme. Or just a default of 1.2f (which looks ok on Carbon).

**Comment by jrassa** [comment] 2017-05-04 17:45
I would vote for setting the default to 1.2f.  We can always revisit and make a change later if it is still a concern for users.  I have been working on a change to properly animate the size change when scrolling and it would be complicated by having to account for 2 different scaling values.

**Comment by pjft** [comment] 2017-05-04 17:47
Sounds good then, that settles it.

A picky question, just to close this off (or, if someone is testing): 1.5 * 0.7 is actually 1.05 .

Does 1.05 look right on screen? It doesn't _sound_ right (too small?), but the maths seem to suggest that would have been the effective multiplier in the past?

Either way, I support the new constant approach. Thanks!

**Comment by zigurana** [comment] 2017-05-04 17:49
Yeah, splitting it up is better, if maybe a bit complicated for themers.
I wonder if that messy situation was put in place to cope with narrow/wide aspect ratio logo's? 
The screenshot on the OP seems to indicate that. 
We should look at how the maxsize is implemented. 

Alternatively, setting the default value to 1.2 is the change with least impact.  
I have no preference either way.

**Comment by joolswills** [comment] 2017-05-04 17:49
Your maths is correct. I guess that's why people noticed when it was 1.5 as before it didn't scale much vertically ? Ill change it to 1.2f

**Comment by zigurana** [comment] 2017-05-04 17:51
@jdrassa, agreed! 
lets keep it at a single (slightly adjusted) value for now.

**Closed by zigurana** 2017-05-04 17:51 UTC
