### ISSUE TITLE
Holding button for navigation gets interrupted by Power Savings

### ISSUE THREAD

**Issue by pjft** [RetroPie/EmulationStation#243] opened 2017-09-17 20:17 UTC
Hi all.

Sorry for submitting rather than fixing - still trying to set up my development environment among everything else.

I noticed today that if I hold a button for navigation (say, down, or R1) that when the PS timeout hits, the navigation will stop. It should be a simple fix - hopefully we're able to detect that a button is still being pressed and as such we count it as a "still pressing a button" event, when counting for PS. Maybe @hex007 will even know exactly where it needs to be checked.

It's easier to replicate if we set it to enhanced or even instant.

Running ES 2.6.3.

I may pick this up in a few weeks after I have everything set up, but thought I'd flag it here for tracking and reference in case someone is looking into doing more things on the PS end.

Thanks.

**Comment by hex007** [comment] 2017-09-17 21:51
To make this handling correction, we can disable PS on key press and re-enable it when key is released. A simple counter can keep track of the number of keys being pressed currently.

@pjft do you think this will work?

**Comment by pjft** [comment] 2017-09-18 05:19
I think it would but it might be a bit more complicated than it needs to. 

From reading the code, InputManager::parseEvent seems to return true if it handles an event, so we might just check for that in the main event loop and if it's true we'd set 

ps_time = SDL_GetTicks();

Once again, needs some testing and debugging (logs?) to make sure that it does return true if a key is pressed and false otherwise, but if that's the case it might be the cleanest way to go about it. 

Turning power savings on and off should probably be avoided if possible:)

**Comment by hex007** [comment] 2017-09-18 16:17
There is already a provision for that https://github.com/RetroPie/EmulationStation/blob/master/es-app/src/main.cpp#L344

In what case does Input manager return false?

**Comment by pjft** [comment] 2017-09-18 16:34
As always, you're correct, which means my suggestion wouldn't work. That's what I get for reading the code on my phone. :)

I suppose, then, that keypress triggers an event, and key release triggers another one, and in between we kind of keep doing whatever it is when the key is pressed.

Perhaps we can detect whether the last event was a key down or up, and if it was down, we keep refreshing the timer, I'm not sure?

Otherwise, sure - turning off PS could work.

Thanks!

**Comment by hex007** [comment] 2017-09-18 16:47
The ideal solution would be to detect if the event is recurring or not and control PS base on that. 

This was a known Issue while writing PS but was skipped as it affected instant and enhanced mostly. The users could workout the trade-offs for those modes.

**Comment by zigurana** [comment] 2017-09-18 17:11
Could we not move the `ps_time = SDL_GetTicks();` statement up inside the
`switch(event.type)` list?
That way the timer keeps being reset while the event lasts.

**Comment by hex007** [comment] 2017-09-18 17:24
No that would not work as each click state is an event. Pressing and releasing the button are different events. You will exit from the loop and get stuck in wait. ES is a single threaded application and hence will only hit the `if (ps_standby...` after the last `ps_time = SDL_GetTicks();`

What i want to try is to detect if the key is pressed or released. This works well for buttons but not for analog sticks as they dont have binary states.

**Comment by psyke83** [comment] 2017-09-19 03:16
Maybe if you take a snapshot of key status inside the switch list via SDL_GetKeyState, and then update the array outside the switch via SDL_PumpEvents & see if SDL_GetTicks(); should be executed depending on whether they key is still pressed? Not sure if that has the same problem with analog sticks.

http://sdl.beuc.net/sdl.wiki/SDL_GetKeyState

**Comment by psyke83** [comment] 2017-09-19 03:46
This fixes the issue for joystick buttons:
```
pi@retropie:~/RetroPie-Setup/tmp/me/EmulationStation $ git diff es-app/src/main.cpp
diff --git a/es-app/src/main.cpp b/es-app/src/main.cpp
index 058121e..dc4f0e2 100644
--- a/es-app/src/main.cpp
+++ b/es-app/src/main.cpp
@@ -343,7 +343,7 @@ int main(int argc, char* argv[])
                        // reset counter
                        ps_time = SDL_GetTicks();
                }
-               else if (ps_standby)
+               else if (ps_standby || event.type == SDL_JOYBUTTONDOWN)
                {
                        // If exitting SDL_WaitEventTimeout due to timeout. Trail considering
                        // timeout as an event
```

On INSTANT PowerSaver mode, holding the dpad down will scroll correctly. Letting go of the pad, emulationstation's CPU reduces to 0.3% almost immediately. So I think you just need to improve this to detect keyboard and axis events too.

**Comment by hex007** [comment] 2017-09-19 05:51
@psyke83 Handling keypress is the easiest thing. Joystick is difficult as there are 1 or 2 press events while only one release event. Some Joysticks have Dpad assigned to JOYHAT event rather than JOYBUTTON. A user might have a different button  for scrolling. Handling all these scenarios makes for complex logic.

**Comment by psyke83** [comment] 2017-09-19 06:01
There's a SDL_HAT_CENTERED that can be used to check in that case. The detection for the multiple event types could just be moved into the else clause without any else condition.

**Comment by hex007** [comment] 2017-09-19 06:02
@pjft I think toggling PS here will work perfectly

https://github.com/RetroPie/EmulationStation/blob/master/es-app/src/components/TextListComponent.h#L245-L275

**Comment by pjft** [comment] 2017-09-19 06:06
Maybe. Is the system carousel also covered by that? Would it not be better
handled in input manager?

**Comment by hex007** [comment] 2017-09-19 06:08
Or possibly exposing this method

https://github.com/RetroPie/EmulationStation/blob/master/es-core/src/components/IList.h#L98

**Comment by joolswills** [comment] 2017-09-19 06:11
@pjft - as mentioned before - is there any chance you not include the quoted text when replying to github via email? (or reply via github).

**Comment by hex007** [comment] 2017-09-19 06:14
@pjft you are leaking your unsubscribe url

**Comment by pjft** [comment] 2017-09-19 06:15
Sorry. Inbox's fast reply doesn't expose any more content, I assumed it
wasn't including it.

**Comment by pjft** [comment] 2017-09-19 06:17
Mobile doesn't allow to edit the post, deleted it instead. 

Something related to iList might be more central indeed. 

Thanks both.

**Comment by hex007** [comment] 2017-09-19 06:24
@pjft try one of the android applications for github.

**Comment by pjft** [comment] 2017-09-20 12:16
I was looking through the code and probably a centralized solution in the main.cpp cycle is the wisest, otherwise we're just sprinkling small changes to different components to make things work as intended.

Can't we start from @psyke83 's solution and build on it as needed? It seems to be the most structured - relying on `event.type == SDL_KEYDOWN || event.type == SDL_JOYBUTTONDOWN`.

**Comment by hex007** [comment] 2017-09-20 16:25
That would be incorrect as that `else if` is only entered if we exit out of wait by timeout. If we add the event.type check there then EVENT will be null at that stage if no event was received for that cycle.

```c++
SDL_Event event;
bool ps_standby = PowerSaver::getState() && SDL_GetTicks() - ps_time > PowerSaver::getMode();

if(ps_standby ? SDL_WaitEventTimeout(&event, PowerSaver::getTimeout()) : SDL_PollEvent(&event))
{
	// Handle EVENT code ...

	// triggered if exiting from SDL_WaitEvent due to event
	if (ps_standby)
		// show as if continuing from last event
		lastTime = SDL_GetTicks();

	// reset counter
	ps_time = SDL_GetTicks();
}
else if (ps_standby)
{
	// If exitting SDL_WaitEventTimeout due to timeout. Trail considering
	// timeout as an event
	ps_time = SDL_GetTicks();
}
```

**Comment by hex007** [comment] 2017-09-20 18:03
@pjft I built the latest unmodified master and I am unable to replicate the bug. Can you provide me which PS mode are you having a problem with. 

@psyke83 Can you try the same on a fresh master try with PS instant and enhanced.

**Comment by psyke83** [comment] 2017-09-20 18:37
The issue can be reproduced with INSTANT. Enter a system list with multiple items and hold the dpad or keyboard down to scroll, and it will only scroll one entry.

When I increased the INSTANT timeout to 800, 100ms etc., it would scroll 2 or 3 entries. Presumably ENHANCED will also cause issues for long lists that would take >3secs to scroll.

I'll have time to recompile w/just the changes I proposed in a few hours and let you know, but I'm confident it'll be the same.

**Comment by psyke83** [comment] 2017-09-20 19:01
If the issue doesn't occur when the input is an axis or hat due to continuous input (doesn't have up/down states), maybe the change I proposed is enough to fix for all cases. Needs testing with other input devices to be sure, though. I also use DualShock3 with the sixad wrapper & the analog sticks don't work at all in ES, so I can't test them.

**Comment by psyke83** [comment] 2017-09-20 19:04
@pjft

The issue occurs on all power modes but analogous to the timeout, right?

https://github.com/RetroPie/EmulationStation/blob/master/es-core/src/PowerSaver.h#L6

INSTANT triggers in 200ms (only enough to scroll one item), ENHANCED after 3 seconds & DEFAULT after 10 seconds.

**Comment by psyke83** [comment] 2017-09-20 21:37
@hex007 

I rebuilt with no other changes but the one-line patch above - it definitely fixes the problem. I also added some debug to PowerSaver::getTimeout() to print when the function is called, and can confirm that the timeout is delayed until the down button or key is released, even on INSTANT.

As I said, the issue can also be reproduced with a standard USB-connected keyboard. I don't have any other controllers to test, so I don't know if axis/hat input is affected by this bug or if the potential fix works for them.

**Comment by hex007** [comment] 2017-09-20 22:04
I am testing it on Fedora Linux PC with keyboard. I will test with joystick and check back. I have no idea how the patch s working. But if it is then I would like to test it with all my gamepads to root out any conflicts. 

Once tested I shall submit a PR.

**Comment by psyke83** [comment] 2017-09-20 22:29
The keyboard repeat my explain why the issue isn't present on keyboard.

As a test, I added this:
```
diff --git a/es-app/src/main.cpp b/es-app/src/main.cpp
index 058121e..acc7dda 100644
--- a/es-app/src/main.cpp
+++ b/es-app/src/main.cpp
@@ -327,6 +327,7 @@ int main(int argc, char* argv[])
                                        case SDL_TEXTEDITING:
                                        case SDL_JOYDEVICEADDED:
                                        case SDL_JOYDEVICEREMOVED:
+                                               if (event.key.repeat) LOG(LogError) << "repeat";
                                                InputManager::getInstance()->parseEvent(event, &window);
                                                break;
                                        case SDL_QUIT:
```
The repeat is reported as you would expect for the keyboard (not reported for a single press, but holding down a key reports it continuously), but oddly enough, the DS3's dpad button presses are always reported as a repeat, even when the button was not pressed before. Also, holding down a button results in a single line printed, not continuous.

**Comment by hex007** [comment] 2017-09-20 22:51
That explains a lot. So a fix is only needed for gamepads and not keyboard.
I tried it with my gamepad (snes usb controller) and the patch fails to handle this correctly.

**Comment by hex007** [comment] 2017-09-20 23:18
This solves the problem @pjft @psyke83 Can you test and get back on this?

```diff
diff --git a/es-core/src/components/IList.h b/es-core/src/components/IList.h

--- a/es-core/src/components/IList.h
+++ b/es-core/src/components/IList.h
@@ -7,6 +7,7 @@
 #include "components/ImageComponent.h"
 #include "resources/Font.h"
 #include "Renderer.h"
+#include "PowerSaver.h"
 
 enum CursorState
 {
@@ -191,6 +192,8 @@ protected:
 
        bool listInput(int velocity) // a velocity of 0 = stop scrolling
        {
+               PowerSaver::setState(velocity == 0);
+               
                // generate an onCursorChanged event in the stopped state when the user lets go of the key
                if(velocity == 0 && mScrollVelocity != 0)
                        onCursorChanged(CURSOR_STOPPED);

```

**Comment by psyke83** [comment] 2017-09-20 23:38
@hex007 It does indeed solve it on DS3, - nice work. I added some debug and see that getTimeout triggers only after the button is released, so it looks fine.

**Comment by hex007** [comment] 2017-09-21 00:12
@pjft Can you test this with the controllers you have?

**Comment by psyke83** [comment] 2017-09-21 00:42
@hex007 

I discovered a bug. On current master, when PS = INSTANT, it's not possible to trigger input configuration using the DS3. When the prompt to hold down the button appears, holding down the button will trigger the display of the device name, but the font will only appear as light grey and never transitions to black. The keyboard is not affected by this issue.

Your patch doesn't fix the issue, but for whatever reason, mine does. Maybe you could also take a look at that since it's most likely related to the root cause of this issue?

**Comment by hex007** [comment] 2017-09-21 01:11
@psyke83 I am unable to get long click scrolling working with your patch. So I cannot use it for testing or as a solution.

Another way to handle this, till where long click should be triggered is found, is to just disable PS while running the input configuration, similar to what is done while scrapper is running.

**Comment by psyke83** [comment] 2017-09-21 01:43
I was suggesting that you check for the issue. I know that my solution is not ideal. Maybe disabling PS is best, otherwise we need something more complex like this:

```
diff --git a/es-app/src/main.cpp b/es-app/src/main.cpp
index 058121e..aabf0b3 100644
--- a/es-app/src/main.cpp
+++ b/es-app/src/main.cpp
@@ -303,6 +303,7 @@ int main(int argc, char* argv[])
        int lastTime = SDL_GetTicks();
        int ps_time = SDL_GetTicks();

+       bool pressed = false;
        bool running = true;
        bool ps_standby = false;

@@ -318,11 +319,29 @@ int main(int argc, char* argv[])
                                switch(event.type)
                                {
                                        case SDL_JOYHATMOTION:
+                                               if (event.jhat.value == SDL_HAT_CENTERED)
+                                                       pressed = false;
+                                               else
+                                                       pressed = true;
+                                                InputManager::getInstance()->parseEvent(event, &window);
+                                                break;
                                        case SDL_JOYBUTTONDOWN:
+                                               pressed = true;
+                                                InputManager::getInstance()->parseEvent(event, &window);
+                                                break;
                                        case SDL_JOYBUTTONUP:
+                                               pressed = false;
+                                               InputManager::getInstance()->parseEvent(event, &window);
+                                                break;
                                        case SDL_KEYDOWN:
                                        case SDL_KEYUP:
                                        case SDL_JOYAXISMOTION:
+                                                if (event.jaxis.value != 0)
+                                                        pressed = true;
+                                                else
+                                                        pressed = false;
+                                                InputManager::getInstance()->parseEvent(event, &window);
+                                                break;
                                        case SDL_TEXTINPUT:
                                        case SDL_TEXTEDITING:
                                        case SDL_JOYDEVICEADDED:
@@ -343,7 +362,7 @@ int main(int argc, char* argv[])
                        // reset counter
                        ps_time = SDL_GetTicks();
                }
-               else if (ps_standby)
+               else if (ps_standby || pressed)
                {
                        // If exitting SDL_WaitEventTimeout due to timeout. Trail considering
                        // timeout as an event
```
This would likely catch everything, but I can't test the jhat condition, and I didn't account for the jaxis deadzone. But it's needlessly complex compared to just disabling PS during input.

**Comment by hex007** [comment] 2017-09-21 01:51
Yea just disabling PS is ideal while running Input Configuration. This certainly is a lot of complexity. I added quick switching PS just for cases where deep integration would be too complex.

**Comment by pjft** [comment] 2017-09-21 08:00
Thanks for all this work.

Happy to test it as soon as I have the chance.

What's the best way to get the de-facto fix on my Pi? Is there a branch with the code to test that I can checkout and test?

Thank you both.

**Comment by hex007** [comment] 2017-09-21 16:38
@pjft Its just addition of 2 lines. here https://github.com/RetroPie/EmulationStation/issues/243#issuecomment-331007257

**Comment by pjft** [comment] 2017-09-24 06:51
This seems to work. Thanks.

**Closed** 2017-09-24 07:17 UTC
