### ISSUE TITLE
Feature Request: option to make filters persist between sessions

### ISSUE THREAD

**Issue by gomisensei** [RetroPie/EmulationStation#702] opened 2020-11-14 05:41 UTC
for example, i especially want to make files ALWAYS hidden when i start up Emulationstation... maybe have an icon letting you know filters are active, or just make hidden roms filter persist.

**Comment by gomisensei** [comment] 2020-11-14 05:44
for example, i especially want to make <hidden> files ALWAYS hidden when i start up Emulationstation... maybe have an icon letting you know filters are active, or just make hidden roms filter persist.

**Comment by cmitu** [comment] 2020-11-15 06:12
Duplicate of https://github.com/RetroPie/EmulationStation/issues/321

**Closed by cmitu** 2020-11-15 06:12 UTC
